### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/saaj-api#14]
- [ ] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [ ] Release to OSSRH staging repository

- [ ] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by Tomas-Kraus** [comment]
PR https://github.com/eclipse-ee4j/saaj-api/pull/15 - waiting for rewiew

**Comment by m0mus** [comment]
Done
https://oss.sonatype.org/content/groups/staging/jakarta/xml/soap/jakarta.xml.soap-api/1.4.1/
