### ISSUE TITLE
Tag changed from 1.4.1-RELEASE to 1.4.1

### ISSUE THREAD

**Issue by wltjr** [eclipse-ee4j/saaj-api#27]
I am not sure why, but seems the tag for 1.4.1-RELEASE was changed to 1.4.1 today. What is the reason for that and will the tag change again? Thank you!

**Comment by wltjr** [comment]
I [packaged this](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/dev-java/javax-xml-soap) a few days ago, and today it failed to download. Seems the change from 1.4.1-RELEASE to 1.4.1 was the reason.

Sorry for the issue mess, I confused myself with an old copy of saaj-1.3.19.tar.bz2. I downloaded and saved 1.4.1-RELEASE.tar.gz as javax-xml-soap-1.4.1.tar.gz. You can [see that part](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/javax-xml-soap/javax-xml-soap-9999.ebuild#L14) in the ebuild itself. With the final file name and digest being recorded in the [manifest](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/javax-xml-soap/Manifest).

**Comment by Tomas-Kraus** [comment]
Tag was changed to comply with internal Jakarta EE rules. Release to maven central was done today so this tag won't be changed anymore.
