### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/saaj-api#28]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by Tomas-Kraus** [comment]
Release job passed: https://jenkins.eclipse.org/jaxws/job/nexus-staging-close/51/console
Created PR to merge release info into EE4J+8 branch: https://github.com/eclipse-ee4j/saaj-api/pull/29
