### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/saaj-api#3]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
I cant prepare release job without GPG, ssh access and OSSRH, but I can prepare some working continuous build.

**Comment by Tomas-Kraus** [comment]
Continuous build is available on https://jenkins.eclipse.org/jaxws/job/saaj-api-master-build/
Build is failing because of wrong GF Copyright plugin configuration.
Created https://github.com/eclipse-ee4j/saaj-api/issues/5 to fix it.

**Comment by Tomas-Kraus** [comment]
Issue #5 is fixed. Build passed.

**Comment by Tomas-Kraus** [comment]
Added https://jenkins.eclipse.org/jaxws/job/saaj-api-ee4j8-build/ and we have the same issue with GF Copyright plugin.

**Comment by Tomas-Kraus** [comment]
Issue #5 backported into EE4J_8, build works.
