### ISSUE TITLE
Merge (original) SOAP Attachments specification source

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/saaj-api#59]
Just an FYI...  The original (oracle) SOAP Attachments specification source is now available via this CQ:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21464

Please import/modify/merge it when time allows, hopefully in time for Jakarta EE 9.  Thanks!

**Comment by kwsutter** [comment]
Part of the work outlined in Jakarta EE 9 Issue #53

**Comment by lukasj** [comment]
fixed by #63
