### ISSUE TITLE
Avoid Jakarta brand for implementations

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/saaj-api#87]
@lukasj An item that came up during our Spec Committee call today was that we should not be using the `Jakarta` brand for naming implementations.  The SOAP compatible implementation was used as an example (but there are others as well).  The URL you used for the Compatible Implementation looks good and references "metro":  https://eclipse-ee4j.github.io/metro-saaj/. But, when you follow that link, you end up on a page that states `Jakarta SOAP with Attachments implementation`.  Instead, you should follow the convention that Bill Shannon did for Activation...  Something like `Eclipse Implementation for Jakarta SOAP with Attachments`.

Or, you could just go with the `Metro` name (which might be more catchy and not such a mouthful.

Since I just submitted the ballot for SOAP, I thought I would just let you know about this issue.  Hopefully, this will not be too big of a change for you.  Thanks!

**Comment by lukasj** [comment]
Metro currently means  former (jaxb+jaxws+saaj+wsit), simply said it is all-in-one web services stack like ie Axis or Apache CXF, while saaj-impl is only its subset which can live and be used just on its own and Metro as such can decide to replace saaj component by a different implementation at any time - there is no implementation dependency between saaj-impl and the rest of the Metro stack.

It feels strange to be using Eclipse Implementation of JAXB, Eclipse Implementation of Jakarta SOAP with Attachments and Eclipse Implementation of Jakarta XML Web Services in one sentence when talking about Metro properly. Do you have any idea how can make these names shorter? Do I have to come up with new codenames which would replace former (JAXB+JAXWS+SAAJ) short names?

**Comment by lukasj** [comment]
btw I changed the name to Eclipse Implementation for Jakarta SOAP with Attachments where appropriate to be able to close this
